// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";     //envを読み取らせるため
import { defineConfig } from "prisma/config";    //バリデーションをかけたり、標準の設定一式を作る

export default defineConfig({
  schema: "prisma/schema.prisma",   //テーブルの形があるパス(schema.prisma)
  migrations: {       
    path: "prisma/migrations",       //マイグレーションファイル(過去のDB変更履歴)がどこにあるか
    seed: "tsx prisma/seed.ts",      //prisma db seedを実行した時に実際に走るコマンド
  },
  datasource: {
    url: process.env["DATABASE_URL"],     //envからもらった値
  },
});
